apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: {{ .Values.namespace }}
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.db.host | quote }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.db.user | quote }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.db.name | quote }}
