name: diplom app CI/CD

on:
  push:
    branches: [ "final" ]
  pull_request:
    branches: [ "final" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven + unit tests
        working-directory: final/diplom-app
        run: mvn -B clean verify

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: final/diplom-app/target/surefire-reports/**

      - name: SonarCloud analys
        working-directory: final/diplom-app
        run: >
          mvn -B
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug JAR
        working-directory: final/diplom-app
        run: ls -la target/

      - name: Set lowercase owner
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push diplom-app image
        uses: docker/build-push-action@v6
        with:
          context: final/diplom-app
          file: final/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/codeby-devops:diplom-app-latest
            ghcr.io/${{ env.OWNER_LC }}/codeby-devops:diplom-app-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
