name: diplom app CI/CD

on:
  push:
    branches: [ "final" ]
#    paths:
#      - "final/**"
  pull_request:
    branches: [ "final" ]
#    paths:
#      - "final/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        working-directory: final/diplom-app
        run: mvn -B clean package -DskipTests

      - name: Debug JAR
        working-directory: final/diplom-app
        run: ls -la target/

#      - name: Upload App artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: diplom-app-jar
#          path: final/diplom-app/target/*.jar

#  build-docker-image:
#    name: Publish to github registry
#    runs-on: ubuntu-latest
#    needs: [build_and_test]

#    permissions:
#      contents: read
#      packages: write

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4

#      - name: Download diplom-app artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: diplom-app-jar
#          path: final/diplom-app/target


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push diplom-app image
        uses: docker/build-push-action@v6
        with:
          context: final/diplom-app
          file: final/Dockerfile
          push: true
          tags: |
            
            ghcr.io/${{ github.repository_owner }}/codeby-devops:diplom-app-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/codeby-devops:diplom-app-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
